"""Initial migration

Revision ID: 882172334a5e
Revises: 
Create Date: 2025-05-23 01:18:05.965000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882172334a5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_graphs_id', 'graphs', ['id'], unique=False, postgresql_using='btree')
    op.create_table('vertices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.CheckConstraint("name ~ '^[a-zA-Z]+$'", name='check_vertex_name'),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_id', 'name', name='uq_vertex_graph_name')
    )
    op.create_index('ix_vertices_graph_id', 'vertices', ['graph_id'], unique=False, postgresql_using='btree')
    op.create_index('ix_vertices_name', 'vertices', ['name'], unique=False, postgresql_using='btree')
    op.create_table('edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_id', sa.Integer(), nullable=False),
    sa.Column('from_vertex_id', sa.Integer(), nullable=False),
    sa.Column('to_vertex_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('from_vertex_id != to_vertex_id', name='check_no_self_loop'),
    sa.ForeignKeyConstraint(['from_vertex_id'], ['vertices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_vertex_id'], ['vertices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_id', 'from_vertex_id', 'to_vertex_id', name='uq_edge_graph_vertices')
    )
    op.create_index('ix_edges_from_vertex', 'edges', ['from_vertex_id'], unique=False, postgresql_using='btree')
    op.create_index('ix_edges_graph_id', 'edges', ['graph_id'], unique=False, postgresql_using='btree')
    op.create_index('ix_edges_to_vertex', 'edges', ['to_vertex_id'], unique=False, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_edges_to_vertex', table_name='edges', postgresql_using='btree')
    op.drop_index('ix_edges_graph_id', table_name='edges', postgresql_using='btree')
    op.drop_index('ix_edges_from_vertex', table_name='edges', postgresql_using='btree')
    op.drop_table('edges')
    op.drop_index('ix_vertices_name', table_name='vertices', postgresql_using='btree')
    op.drop_index('ix_vertices_graph_id', table_name='vertices', postgresql_using='btree')
    op.drop_table('vertices')
    op.drop_index('ix_graphs_id', table_name='graphs', postgresql_using='btree')
    op.drop_table('graphs')
    # ### end Alembic commands ###
